server:
  port: 8080

spring:
  application:
    name: disaster-app

jena:
  fuseki:
    query-url: ${FUSEKI_URL:http://localhost:3030}/disaster/query
    update-url: ${FUSEKI_URL:http://localhost:3030}/disaster/update
    data-url: ${FUSEKI_URL:http://localhost:3030}/disaster/data
    admin-url: ${FUSEKI_URL:http://localhost:3030}/$/datasets
    dataset-name: disaster
